### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by sconwayaus** [eirikpre/VSCode-SystemVerilog#113]
Hi,

Updated to version 11 and noticed a few odd things with the syntax highlighting. I've screen grabbed version 0.11.2 (latest as of today on the right) and version 0.10.11 (left).

![Screenshot 2021-02-01 140130](https://user-images.githubusercontent.com/6986019/106410320-b802df00-6496-11eb-9efc-d89be8b28ae4.png)

Case statement shows different colors of STATE_1 an STATE_2 on line 32.

FWIW, I also preferred the light green used for the parameter and names in the enumeration (lines 2, 3 and 12-16).

As an aside, the new highlighter didn't pick up that I typed "parameter" incorrectly on lines 2 and 3, where as the old syntax highlighting did.

**Comment by jecassis** [comment]
Thank you for the example. Found a couple of other cases that needed correcting and will push an update. Specifically from the example line 32 has already been fixed by the `port-net-parameter` grammar. Also note that `typedef enum unsigned int` is not legal according to my reading of the LRM. The `unsigned` keyword should go last in this case.

As for the color preference, all the syntax highlighting does is classify each tokens to a specific scope. The colors are determined by your theme. You can override the theme's colors using `editor.tokenColorCustomizations` in `settings.json` to suit your tastes. For example the `STATE_*` parameters you mention are classified as `constant.other.net.systemverilog`. Note that this does not include any semantic information. To find the scope for each token run `editor.action.inspectTMScopes`.

The example from this issue using a minimally-modified One Dark Pro theme is shown below:

<img width="225" alt="formatting" src="https://user-images.githubusercontent.com/36133/106432468-9e747f80-6423-11eb-9c50-812d29e19386.png">

**Comment by sconwayaus** [comment]
Thanks Jecassis,

You're right, enum should be "int unsigned" and thanks for the tip on the
theme settings. Looking forward to the update.

Cheers
Steve

**Comment by bitrocco** [comment]
There is a related syntax highlighting issue.

When the definition of `enum` type is written on one line, the syntax highlighting is wrong, but it is correct in lowercase, as shown below:

![image](https://user-images.githubusercontent.com/30104601/106855590-20043000-66f8-11eb-98a1-0686f106ba05.png)

**Comment by jecassis** [comment]
Thanks @sconwayaus. @bitrocco, single-line typedefs like this are fixed in #112. That said, let me clarify what you should expect. There is a small concession made in the syntax matcher to mark identifiers in all caps using the constant classification/coloring. Without semantic information, the matcher prioritizes this as a best guess based on the various coding styles I have come across in the industry such as [this one](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md). Many lint tools even enforce these kind of conventions in their [default ruleset](https://google.github.io/verible/lint.html#parameter-name-style).

![Typedef enums](https://user-images.githubusercontent.com/36133/106857284-aecf6900-6674-11eb-90f5-f9c95cb8e96a.png)

**Comment by bitrocco** [comment]
@jecassis Thanks for your reply.

Sorry for the previous unclear explanation, but the original intention is that the enum_identifier in the enumeration declaration should have the same highlight color. However, the #112 solution is also accepted, because it generally follows the same code style. So look forward to the next version update :smile:.

**Comment by eirikpre** [comment]
Should be ok with the last release 0.11.3 :)
