### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by CatWithoutBoots** [eirikpre/VSCode-SystemVerilog#21]
Can you add a capatibility for work with "Go to" for tasks and functions?

**Comment by eirikpre** [comment]
This is something I have wanted to add, but there hasn't really been time.

At the moment I only see it being able to Go to tasks/functions within the current file.

**Comment by eirikpre** [comment]
*Update
> At the moment I only see it being able to Go to tasks/functions within the current file.
has been working since v0.5, at the very least.
Global go to definition, not yet

**Comment by eirikpre** [comment]
Heya, I would previously not add this because indexation in big workspaces would take forever.

But it is now aware of workspace size, so if you have:
less than `settings.parallelProcessing*1000` it will index all global tasks/events/typedef++.
less than `settings.parallelProcessing*100` it will index all global tasks/events/typedef++ including one hierarchy inside found global signals(eg file:class->function, instead of just file:function)

**Comment by eirikpre** [comment]
edit: less than `settings.parallelProcessing*XXXX` as in number of `**/*.{v,sv} files in workspace
