### ISSUE TITLE
ModelSim or QuestaSim as Linters 

### ISSUE THREAD

**Issue by ldm1417** [eirikpre/VSCode-SystemVerilog#93]
Hello, 

As the Compile Type, there are only two options in the extension settings - Verilator and VCS. 

Is this possible to add also the ModelSim and QuestaSim as a Linter? How to? 

Thank you!

**Comment by eirikpre** [comment]
Heia!

I plan to remove all tool support, and otherwise explain how this can be done with a task and a run-on-save extension.Supporting tools is unnecessary and boring work, so I plan to only leverage the extension's own features.

Does this answer your question?
https://github.com/eirikpre/VSCode-SystemVerilog/issues/79 
see the link to https://github.com/eirikpre/VSCode-SystemVerilog/issues/63#issuecomment-618331523

BR Eirik
